import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Admin",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "User",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      // _id: '2',
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '3',
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      // _id: '4',
      name: "Adidas Fit Pant",
      slug: "adidas-fit-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Levi's Regular Jeans",
      slug: "levis-regular-jeans",
      category: "Jeans",
      image: "/images/p3.jpg",
      price: 90,
      countInStock: 8,
      brand: "Levi's",
      rating: 4.2,
      numReviews: 12,
      description: "classic denim jeans",
    },
    {
      name: "Puma Casual Shirt",
      slug: "puma-casual-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 80,
      countInStock: 6,
      brand: "Puma",
      rating: 4.3,
      numReviews: 10,
      description: "casual wear shirt",
    },
    {
      name: "Adidas Training Pants",
      slug: "adidas-training-pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 55,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 8,
      description: "comfortable training pants",
    },
    {
      name: "Nike Sport shirt",
      slug: "nike-sport-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 40,
      countInStock: 20,
      brand: "Nike",
      rating: 4.4,
      numReviews: 15,
      description: "breathable sport shirt",
    },
  ],
};
export default data;
