import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Admin",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
      isSeller: true,
    },
    {
      name: "User",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
      isSeller: true,
    },
  ],
  categories: [
    {
      name: "Clothing",
      slug: "clothing",
    },
    {
      name: "Manufacturers",
      slug: "manufacturers",
    },
    {
      name: "Electronics",
      slug: "electronics",
    },
    {
      name: "Cosmetics",
      slug: "cosmetics",
    },
    {
      name: "Furniture",
      slug: "furniture",
    },
    {
      name: "Construction Tools",
      slug: "construction_tools",
    },
    {
      name: "Industrial Machinery",
      slug: "industrial_machinery",
    },
    {
      name: "Car accessories",
      slug: "car_accessories",
    },
    {
      name: "Sports & Entertainment",
      slug: "sports_entertainment",
    },
    {
      name: "Home and garden",
      slug: "home_and_garden",
    },
    {
      name: "Gaming",
      slug: "gaming",
    },
  ],
  products: [
    {
      name: "Nike Sport shirt",
      slug: "nike-sport-shirt",
      category: "Clothing",
      image: "/images/p2.jpg",
      price: 40,
      countInStock: 20,
      brand: "Nike",
      rating: 4.4,
      numReviews: 15,
      description: "breathable sport shirt",
    },
    {
      name: "Adidas Fit Pant",
      slug: "adidas-fit-pant",
      category: "Clothing",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Levi's Denim Jacket",
      slug: "levis-denim-jacket",
      category: "Manufacturers",
      image: "/images/p1.jpg",
      price: 90,
      countInStock: 15,
      brand: "Levi's",
      rating: 4.6,
      numReviews: 18,
      description: "classic denim jacket for all occasions",
    },
    {
      name: "Tommy Hilfiger Polo Shirt",
      slug: "tommy-hilfiger-polo-shirt",
      category: "Manufacturers",
      image: "/images/p3.jpg",
      price: 55,
      countInStock: 10,
      brand: "Tommy Hilfiger",
      rating: 4.3,
      numReviews: 12,
      description: "stylish and comfortable polo shirt",
    },
    {
      name: "Apple Iphone 15",
      slug: "apple-iphone-15",
      category: "Electronics",
      image: "https://mobilecare.gecora.com/images/feature/item-00.jpg",
      price: 999,
      countInStock: 10,
      brand: "Samsung",
      rating: 4.8,
      numReviews: 25,
      description: "powerful smartphone",
    },
    {
      name: "Apple MacBook Pro",
      slug: "apple-macbook-pro",
      category: "Electronics",
      image: "https://mobilecare.gecora.com/images/feature/item-01.jpg",
      price: 1499,
      countInStock: 15,
      brand: "Apple",
      rating: 4.7,
      numReviews: 20,
      description: "high-performance laptop",
    },
    {
      name: "Luxury Makeup Set",
      slug: "luxury-makeup-set",
      category: "Cosmetics",
      image:
        "https://media.ulta.com/i/ulta/2554717?w=240&$ProductCardNeutralBGLight$",
      price: 150,
      countInStock: 5,
      brand: "Luxury",
      rating: 4.6,
      numReviews: 10,
      description: "premium makeup collection",
    },
    {
      name: "Organic Skincare Kit",
      slug: "organic-skincare-kit",
      category: "Cosmetics",
      image: "https://media.ulta.com/i/ulta/2610923?w=720&h=720&fmt=webp",
      price: 120,
      countInStock: 8,
      brand: "Organic Beauty",
      rating: 4.5,
      numReviews: 12,
      description: "natural skincare essentials",
    },
    {
      name: "Elegant Sofa",
      slug: "elegant-sofa",
      category: "Furniture",
      image:
        "https://mehshaninteriors.com/wp-content/uploads/2022/10/sofa-16-01-1200x1200.jpg",
      price: 799,
      countInStock: 8,
      brand: "HomeDecor",
      rating: 4.2,
      numReviews: 12,
      description: "comfortable and stylish sofa",
    },
    {
      name: "Modern Coffee Table",
      slug: "modern-coffee-table",
      category: "Furniture",
      image:
        "https://mehshaninteriors.com/wp-content/uploads/2022/10/sofa-16-01-1200x1200.jpg",
      price: 299,
      countInStock: 15,
      brand: "Contemporary Living",
      rating: 4.7,
      numReviews: 20,
      description: "sleek and minimalist design",
    },
  ],
};
export default data;
